name: Node.js CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          queries: +security-extended, security-and-quality
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3.9.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: altablearn@gmail.com
          
