name: Node.js CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          queries: +security-extended, security-and-quality
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Send email
        if: always()
        shell: pwsh
        run: |
          $sendMailMesssageSplat = @{
            From = 'altablearn@gmail.com'
            To = 'altab_h@pursuitsoftware.biz'
            Subject = 'Github Actions - Tosca Test Summary Update'
            Body = 'Build job of ${{github.actor}} completed successfully!'
            Priority = 'High'
            DeliveryNotificationOption = 'OnSuccess', 'OnFailure'
            SmtpServer = 'smtp.gmail.com'
            port = 587
            Credential = (New-Object pscredential ("altablearn@gmail.com", (ConvertTo-SecureString -AsPlainText -String "fyturmabxagluiav" -Force)))
          }
          Send-MailMessage $sendMailMessageSplat       
          
